### ISSUE TITLE
[BUG] Can't add new items to dictionary with AtomVariables as keys

### ISSUE THREAD

**Issue by iruizmar** [AdamRamberg/unity-atoms#95] opened 2019-12-01 20:43 UTC
**Describe the bug**
Found this using Odin Serializer. Given a dictionary with FloatVariable as key type, when two FloatVariables has the same value, even if they are different instances, Odin will not allow you to add the second one to the dictionary, saying "An item with the same key already exists".

Tried this with IntVariable and it's happening too, but it's not with custom ScriptableObjects. My guess is that it's something with AtomVariable returning _value in the default get. I'm not really sure how to fix this without decreasing notably the ease of use of the AtomVariables.

**Expected behavior**
Compare instances instead of values and so, Odin will allow to add the second instance to the dictionary.

**Screenshots**
![unknown](https://user-images.githubusercontent.com/11753209/69920019-75eda000-1483-11ea-9eab-8c57de8f0844.png)

**Environment**
 - OS: Windows
 - Unity Version: 2019.2.14f
 - Version of Unity Atoms 2.1.0

**Comment by AdamRamberg** [comment] 2019-12-02 20:13
Thanks for submitting this bug! For me the current behaviour is correct, if the value of a Variable is the same as another Variable then they are equal. I don't really see why you would use objects as keys in a dictionary. Do you have a use case where you actually want to refer to a Variable as the key instead of a "primitive" like a number, string, etc?

**Comment by SugoiDev** [comment] 2019-12-03 09:09
I'm not sure if the actual instance should be disregarded in equality.
I've used many containers before, and I only do that when the inner data is all that matters. I think the actual instance in the case of atoms also matter, so maybe that behavior is not ideal.
Maybe the actual instance is **all** that matters for equality in this case.

The unexpected behavior that @Saso222 noticed will happen in hashed collections, not only dictionary. It can cause really odd behaviors too, since GetHashCode will change when the underlying value changes.

---

About dictionary keys, I don't know @Saso222's specific use-case, but I use objects as keys in dictionaries all the time.

Here's a specific case from a real project of mine: game flags.
My game's flags are ScriptableObjects.
I might have 2 gameFlags that *now* have the same internal values, but they represent different flags.
For example, the amount of wood and grass a player has collected might both have an int with value 0, but those flags are not the same. The actual instance matters.

A couple reasons why I might want to add them to a map

* grouping in the inspector, so the designer can easily see the flags and maybe filter the list for easier editing. My dictionaries have draggable key-value headers so I want to be able to use that.

* to filter flags using LINQ. I might want to see all flags that match a criteria, and LINQ can be useful here. Having a dictionary keyed on the actual ScriptableObject can be useful when filtering. For example, I could filter by interface to get only ISaveable flags when I'm going to save the game.

**Comment by Saso222** [comment] 2019-12-09 10:20
Hey, sorry for the delay.

Well, yes, exactly what @SugoiDev said.

I'm using AromVariables as instance representations of, for example the amount of a certain resource the player has on a RTS. This way, the building class has a dictionary of resources it costs and the amount, in order to give the designer the possibility to adjust those values.

That's not the only place where I'm using Variables as semantic representations of an entity, I have more.
 
A workaround would be to create an envoloe object that holds those Variables, even if the envelope is otherwise empty. But I thought this behaviour was unintended and so I reported it.

Thanks

**Comment by SugoiDev** [comment] 2019-12-09 10:51
Another possible workaround would be creating the map itself with a custom equality comparer that does object comparisons.

If you're serializing the map, you would have to check if your serializer supports serializing the comparer as well.

**Comment by AdamRamberg** [comment] 2020-01-23 19:54
So after some thinking I have to say that I agree with your arguments, it should definitely be possible to add atoms with the same value to a collection. I will look into this when I have the time or if someone else is up for it I would really appreciate a PR.

**Comment by AdamRamberg** [comment] 2020-02-18 22:26
PR #111 created to address this issue.

**Comment by AdamRamberg** [comment] 2020-02-23 01:23
Fixed in #111 that just merged to canary. Fix will be included in next release of Unity Atoms.

**Closed by AdamRamberg** 2020-02-23 01:23 UTC
Labels: bug, has PR, ready to be developed
