### ISSUE TITLE
[BUG] Editing Value of Unity Atom in Editor immediately reverts value to Initial

### ISSUE THREAD

**Issue by Sparkky** [AdamRamberg/unity-atoms#69] opened 2019-10-29 03:11 UTC
**Describe the bug**
You cannot edit the value of a variable in the editor  as soon as you change focus the value immediately reverts to Initial Value, furthermore if you do this while the game is playing, no update event will fire.

**To Reproduce**
1. Create blank project with just Unity Atoms 2.0
2. Create a Unity Atom (Int for this example)
3. try to change "Value" of the Atom
4. as soon as you change focus / hit enter the value will revert to Initial value

**Expected behavior**
You can change value in editor and the value will change, Ideally if there is an associated event and the game is running it should fire that event.

**Environment**
 - OS: windows 10
 - Unity Version 2019.2.9
 - Unity Atoms v 2.0.0

**Additional context**
If the value was changed by another script, everything works as expected, you can watch the value update in the editor drawer.

**Comment by soraphis** [comment] 2019-10-29 07:32
if not in playmode: change the initial. 

if in playmode: when you're changing things directly in editor this is done via unitys serialization system it does not call the setter method and thus it does not send events. on the event there is a button to manually send an event from the editor.

this is expected behavior.

though: this could be made clearer for the user. will look into this

**Comment by AdamRamberg** [comment] 2019-10-30 21:45
Thanks for submitting this issue! 

Elaborating on what @soraphis is saying, we should definitely look this over. In my mind the optimal UX would be if: 
- **Value** - always editable both in edit mode and play mode. If possible it should trigger a change event when changed in play mode. 
- **Initial Value**  - always editable both in edit mode and play mode.
- **Old Value** - has not been part of the discussion above, but want to add this to the discussion since it is still a part of the UX of the Variable's editor. I think this one should be visible , but never editable. Maybe we should add something like [this](https://answers.unity.com/questions/489942/how-to-make-a-readonly-property-in-inspector.html). Should we create a separate issue for this? 

To solve the immediate problem described by @Sparkky I think it would be ok to move the assignment of `_value` to `_initialValue` from `OnAfterDeserialize` to the beginning of `OnEnable`. This at least works great for me when running in the editor, but not 100% sure that this behaves correctly in builds.

**Comment by soraphis** [comment] 2019-10-31 06:25
I'm working on a Custom editor:

- Old Value is never editable (does not make sense)
- Value is only ediable in playmode and triggers a change event.
- Initial Value is only ediable in edit mode (and also changes value along)

changing the initial value in runtime seems weird to me ... because its the "design time start value", but as i think about it, this could be a valid use case

> To solve the immediate problem described by @Sparkky I think it would be ok to move the assignment of _value to _initialValue from OnAfterDeserialize to the beginning of OnEnable. This at least works great for me when running in the editor, but not 100% sure that this behaves correctly in builds.

I'm not sure about that :/ and since my extension is mostly finished (a last test this evening, and tomorrow at this time there should be a PR) this shouldn't be necessary

**Comment by AdamRamberg** [comment] 2019-10-31 09:17
@soraphis Cool! Sounds like a better long term solution! Looking forward to the PR 👌

**Comment by AdamRamberg** [comment] 2019-11-03 14:39
Assigning @soraphis to the issue since he is working on it in #69

**Comment by AdamRamberg** [comment] 2019-11-14 12:01
Fixed in #70. Closing the issue.

**Closed by AdamRamberg** 2019-11-14 12:01 UTC
Labels: bug
