### ISSUE TITLE
[BUG] Collection serialized keys are not clearing on collection clear.

### ISSUE THREAD

**Issue by mutmedia** [AdamRamberg/unity-atoms#205] opened 2020-10-27 14:31 UTC
**Describe the bug**
Collection serialized keys are not clearing on dictionary clear, causing the inspector to be very populated after multiple iterations of a game adding the same key to the dictionary (big possibility of crashing unity on attempting to inspect)

**To Reproduce**
1. Create a script that adds elements to an AtomCollection `collection.Value.Add(key, value)`
2. Create a script that clears the same AtomCollection `collection.Value.Clear()`
3. Observe the AtomCollection inspector while that's being done
4. Debug the collection to see it's actually empty after clear, even if the inspector shows elements

**Expected behavior**
The inspector should be cleared when the collection is cleared

**Environment**
 - OS: Windows
 - Unity Version 2019.4.9
 - Version of Unity Atoms 4.3.0

**Comment by soraphis** [comment] 2020-10-28 16:19
duplicate of https://github.com/AdamRamberg/unity-atoms/issues/204

**Closed by soraphis** 2020-10-28 16:19 UTC
Labels: bug
