### ISSUE TITLE
all GameEventListener's don't allow passing a dynamic parameters to callback

### ISSUE THREAD

**Issue by Pavelko007** [AdamRamberg/unity-atoms#54] opened 2019-09-25 11:52 UTC
I encountered a problem that I can't pass dynamic value in the callback.
Fortunately, I found a cause and a solution.
To fix the issue require to modify GameEventListener file. 
change this
` [SerializeField]        private UER UnityEventResponse = null;`
to this
` public UER UnityEventResponse = null;`

Need to do this in both classes.
I think those two classes need to be refactored to extract a common code.

**Comment by soraphis** [comment] 2019-09-25 12:40
not sure if related to https://github.com/AdamRamberg/unity-atoms/issues/51#issuecomment-521018393

will look later this week into this

**Comment by soraphis** [comment] 2019-09-26 06:03
the field is private by design (same for the list) 
while I personally don't use the Inspector-driven event system that often, i wonder whats your use-case.
why switch the event response at all?

you could simply put it all in the component that should do the switching (registering / unregistering different responses, when needed) see #51 because it goes into a similar direction.

On the other hand, this is a Library and we shouldn't necessarily force the user to a specific workflow (unless there is a good reason to).

**Comment by AdamRamberg** [comment] 2019-09-26 06:27
@Pavelko007 Thanks for submitting the issue. @soraphis Great that you look into the issue ⭐️ 

Without investigating further, not sure how changing from:
`[SerializeField] private UER UnityEventResponse = null;`
to
`public UER UnityEventResponse = null;`
changes the behaviour and allows you to pass a dynamic variable. Do you have any ideas on how this could be? @Pavelko007

**Comment by soraphis** [comment] 2019-09-26 19:05
> Without investigating further, not sure how changing from:

because he is changing the value by script. there is not setter-like method, so with it being private this is not possible.

**Comment by SpeedHighway** [comment] 2019-09-29 03:25
It's very likely that this is related to this issue.
https://issuetracker.unity3d.com/issues/events-generated-by-the-player-input-component-do-not-have-callbackcontext-set-as-their-parameter-type
However, I've moved to 2019.3.0b4 to try and resolve it and it still doesn't work for me.  (I was doing this manually and switched to your library in the hopes that I was doing something wrong.  

When it fails, it seems like it's even failing to figure out the type because the UI in the inspector states "Unity Event Response ()" instead of using a type like "Unity Event Response (Single)".

**Comment by markcastle** [comment] 2019-09-30 12:11
Not sure it's completely related by that issue on event tracker.  I've found that everything works fine in Unity 2019.2.4f1....

![2019-2-4f1](https://user-images.githubusercontent.com/5383466/65877185-ea706980-e382-11e9-850a-6729f787ba0a.PNG)

but doesn't work in 2019.3.0b4...

![2019-3-0b4](https://user-images.githubusercontent.com/5383466/65877434-97e37d00-e383-11e9-9f4c-69b55680b826.PNG)

However, if I create a simple UnityEvent with any type of generic params I have no issues hooking that up in the inspector to dynamic events, so hence the somewhat tentative conclusion that it's not entirely an issue in Unity 2019.3.0b4 - but I could be wrong.

**Comment by markcastle** [comment] 2019-09-30 12:21
....actually Pavelko007's workaround also works in canary...

Edit AtomListener.cs

public UER _unityEventResponse = null;

for both....

public abstract class AtomListener<T, GA, E, UER>
public abstract class AtomListener<T1, T2, GA, E, UER>

That has been driving me nuts for a little while. Thanks for that workaround :-)

Working in Unity 2019.3.0b4...
![2019-3-0b4-working](https://user-images.githubusercontent.com/5383466/65878095-273d6000-e385-11e9-9e6f-f48927b3e8d5.PNG)

**Comment by AdamRamberg** [comment] 2019-10-09 11:00
> because he is changing the value by script. there is not setter-like method, so with it being private this is not possible.

Alright, I was a little confused at first, thought we were talking about [dynamics](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic). If I understand you correctly then you want to add an `UnityEvent`at runtime to a listener? Eg: `listener.UnityEventResponse.AddListener((v) => { });`

@Pavelko007 Why can't you just use the Event hooked up to listener and do this instead? Eg: `event.Register((v) => {});`

> One use case scenario I could think of would be:
> 
> Think of a pickable object. whoever carries it regenerates health per ticks. those ticks invoke the event of this item

The above would work in that scenario, right? ☝️ 

------

I think what @SpeedHighway and @markcastle are talking about is another issue where there is a problem assigning methods to the listener via the inspector. Making the variables public might make it work, eg: `public UER _unityEventResponse = null;`I don't really like that approach though if it's possible to avoid it. It is private by design. Will look into the issue later this week. (Please let me know if I haven't understood the issue correctly)

**Comment by soraphis** [comment] 2019-10-10 06:31
> The above would work in that scenario, right? ☝️

(I might be wrong, have not tested it, but) you'd need to unregister all the other ones, which the other way you would not. right?

> I think what @SpeedHighway and @markcastle are talking about is another issue where there is a problem assigning methods to the listener via the inspector. [...]  don't really like that approach though if it's possible to avoid it. It is private by design. 

Yeah, exactly my thoughts on this.

Unity 2019.3 is a beta release, this should be a bug report to Unity imho

**Comment by markcastle** [comment] 2019-10-12 22:24
@AdamRamberg & @soraphis Indeed it was only an issue in Unity 2019.3, not sure if fixed by Unity in later as not had a chance to have a look.  Indeed also 'dynamic' in this case refers to dynamic invocation of UnityEvents and the issue was purely when trying to hook them up in the inspector. As you can see from my previous screen shots the type 'Collider2D' in this case wasn't showing in the inspector hence Unity wasn't showing any dynamic calls that are valid for the Collider2D so we were unable to hook anything up in the inspector.

Screen shots below show it correctly working

Agree this is a Unity Bug but I needed a workaround and Pavelko007's workaround did the trick for me.

![DynamicParams1](https://user-images.githubusercontent.com/5383466/66708363-4eae0880-ed47-11e9-92b1-ffcc481ee1e1.PNG)
![DynamicParams2](https://user-images.githubusercontent.com/5383466/66708364-51a8f900-ed47-11e9-94cf-b34a71fa714b.PNG)

**Comment by AdamRamberg** [comment] 2019-10-16 16:17
Made the`_unityEventResponse` public as a temporary workaround due to the Unity bug. Fix is implemented in 14f02a998e69916f8abf711f996bb32c2fba6c55. 

> (I might be wrong, have not tested it, but) you'd need to unregister all the other ones, which the other way you would not. right?

It's the same in both cases, you will need to unregister the handler manually. Will close the issue for now, reopen if you don't agree.

**Closed by AdamRamberg** 2019-10-16 16:17 UTC
