### ISSUE TITLE
[FEATURE] Let us modify BaseEventReferenceListener ReplayEventBufferOnRegister in code

### ISSUE THREAD

**Issue by TowerCrow** [AdamRamberg/unity-atoms#197] opened 2020-10-06 19:59 UTC
**Is your feature request related to a problem? Please describe.**

I want to change ReplayEventBufferOnRegister bool via code when setting up new event listeners, I can't do that right now since it's private.

**Describe the solution you'd like**

Make ReplayEventBufferOnRegister accessable and changeable in code.

**Describe alternatives you've considered**

Have ReplayEventBufferOnRegister be disabled by default.

**Comment by soraphis** [comment] 2020-10-06 21:00
duplicate of: https://github.com/AdamRamberg/unity-atoms/issues/194

**Closed by soraphis** 2020-10-06 21:00 UTC
Labels: enhancement
